# Generated by Django 3.2.6 on 2021-08-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['-likes']},
        ),
    ]
