# Generated by Django 3.2.6 on 2021-08-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_fact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='fact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.fact'),
        ),
    ]
