# Generated by Django 3.2.6 on 2021-08-28 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_photo_fact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='fact',
            name='likes',
        ),
        migrations.AddField(
            model_name='fact',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 28)),
        ),
    ]
