# Generated by Django 3.2.6 on 2021-08-28 22:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210828_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 28, 22, 41, 52, 936255, tzinfo=utc)),
        ),
    ]
