# Generated by Django 3.2.6 on 2021-08-29 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_fact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 18, 20, 52, 74148, tzinfo=utc)),
        ),
    ]
